### ISSUE TITLE
R is taking longer to start than usual

### ISSUE THREAD

**Issue by paolo-kunderfranco** [grst/rstudio-server-conda#10]
Hi,

I followed your nice script to bypass limitations of free rstudio server.
Actually I cannot manage to run it properly,

### /home/pkunderfranco/.conda/envs/Scenic_1.1.2.2

once I open in the web brower port 8008, R is not responding and keep loading,

Any suggestion?

Best
Paolo

**Comment by grst** [comment]
try to do
```
killall rsession
```
and delete everything from `~/.rstudio/ressions`

**Comment by paolo-kunderfranco** [comment]
I killed all sessions, and deleted everything from
`.rstudio/sessions,` in my home directory.
Is it correct? (you wrote rsessions)

still not responding

Paolo

**Comment by grst** [comment]
Yeah, that's correct.
No idea then, sorry

**Comment by paolo-kunderfranco** [comment]
Different users in the same machine could run the command in different ports, am I correct?

**Comment by grst** [comment]
Yes, that should work

**Comment by paolo-kunderfranco** [comment]
no idea, it was working yesterday, then no more this morning, something crashed

**Comment by grst** [comment]
I think this can be closed. If you are still having issues, you could also give the containerized approach a try that I just added to the README.
