### ISSUE TITLE
Permission problems with 1.4

### ISSUE THREAD

**Issue by Finesim97** [grst/rstudio-server-conda#11]
Hi,
I have used your scripts to run Rstudio server in my docker container setup, thank you so much! But with the new 1.4 release of RStudio, they changed something when it comes to the sqlite database. I don't know why this only becomes a problem with the newest release. 

After the update, Rstudio server just exited after starting and reports:

```
"ERROR database error 7 (sqlite3_statement_backend::loadOne: attempt to write a readonly database) [description: Could not delete expired revoked cookies from the database, description: Could not read revoked cookies from the database]; OCCURRED AT virtual rstudio::core::Error rstudio::core::database::Connection::execute(rstudio::core::database::Query&, bool*) src/cpp/core/Database.cpp:480; LOGGED FROM: int main(int, char* const*) src/cpp/server/ServerMain.cpp:729
```

This seems to be related to https://community.rstudio.com/t/permissions-related-to-upgrade-to-rstudio-server-open-source-1-4/94256/3 and https://github.com/rocker-org/rocker-versioned2/issues/105

The directory `/var/lib/rstudio-server` contains the sqlite file (`/var/lib/rstudio-server/rstudio.sqlite`) which needs to be writeable by the user running the server and has a default system daemon user GID UID set by the installer (at least in the deb file). 

I fixed it by giving the file to my user executing rstudio server, but deleting the file and allowing other users to write in the parent directory apparently also works.

The better fix may be to give rstudio server the `--database-config-file arg` flag and provide a config file like this 
```
directory=/var/lib/rstudio-server 
```
In the default file, all options are commented, so it is basically empty. 

Hopefully this helps someone,
Lukas Jansen

**Comment by davidspek** [comment]
@Finesim97 I think this might also be helpful here. 
https://github.com/rocker-org/rocker-versioned2/issues/105#issuecomment-791638147
