### ISSUE TITLE
ERROR after rstudio-server update

### ISSUE THREAD

**Issue by FcoughN** [grst/rstudio-server-conda#16]
Thank you for the tool, it helped me a lot.
However,after I upgrade the rstudio-server, it seems there are some errors. 

> [rserver] ERROR Attempt to run server as user 'rstudio-server' (uid 999) from account 'aaa' (uid 1006) without privilege, which is required to run as a different uid; LOGGED FROM: virtual rstudio::core::ProgramStatus rstudio::server::Options::read(int, char* const*, std::ostream&) src/cpp/server/ServerOptions.cpp:322

Looking forward to your reply.

**Comment by grst** [comment]
which of the three approaches (local, singularity, podman) are you using?
and
what's the version of rstudio server you are running now?

**Comment by FcoughN** [comment]
Thanks for your reply ! 

I am using the local with
`./start_rstudio_server.sh 5656` 

the rstudio-server version is
> 2021.09.0+351 (Ghost Orchid) for Ubuntu Bionic

**Comment by mrartanis** [comment]
Looks like this: https://github.com/grst/rstudio-server-conda/pull/18 should help

**Comment by grst** [comment]
Hi @Mt-cn, could you please check if @mrartanis' solution fixes the problem for you? It is now merged into the master branch.
