### ISSUE TITLE
running rserver on computational node

### ISSUE THREAD

**Issue by Zepeng-Mu** [grst/rstudio-server-conda#17]
Hi, 
I'm very new to docker but I already find your repo greatly helpful.
I'm using a HPC system that I do not have root privilege, so I installed Singularity using conda.
Now I can run rserver in the login node. But what I really want to do is to be able to start a SLURM job and run RStudio server there.
When I tried to do this, I got the error:
```
FATAL:   while extracting rstudio_4.0.5.sif: root filesystem extraction failed: extract command failed: ERROR  : Failed to create user namespace: user namespace disabled
: exit status 1
```
I have no idea what this means. I tried the solution from rocker project page, and it's the same.
Therefore I'm wondering how should I run RStudio server in a computational node?

Thanks so much!

**Comment by grst** [comment]
In principle I think your approach is fine, but I never encountered this issue before. 
Maybe it's better to ask this question in the rocker repository, as I don't think it's specific to the conda part.

**Comment by Zepeng-Mu** [comment]
Hi, thanks for the quick reply.
After some reading I found a Singularity issue on it's GitHub page that says this is because security feature after 3.6.4.
After downgrading from 3.7.1 to 3.6.3 I no longer see this error message.
I will close this issue for now, but maybe this is useful to other people as well.
