### ISSUE TITLE
rsession does not recognize conda environment packages

### ISSUE THREAD

**Issue by jtelleriar** [grst/rstudio-server-conda#2]
rsession does not recognize conda environment packages

**Comment by grst** [comment]
Hi, 

thanks for reporting. 
Can you please provide a detailed error message and a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by jtelleriar** [comment]
I included the fix in my fork:

https://github.com/jtelleriar/rstudio-server-conda

Best,
Juan

**Comment by jtelleriar** [comment]
I am using Redhat Linux
