### ISSUE TITLE
error when trying to enter singularity started rstudio-server

### ISSUE THREAD

**Issue by TTTPOB** [grst/rstudio-server-conda#20]
## step to reproduce
1. clone this repo
2. run `PORT=11231 PASSWORD=112233 ./run_singularity.sh`
3. go to `http://localhost:11231`
4. enter username and password

## result
![image](https://user-images.githubusercontent.com/19909103/141107859-68b49d52-7f4c-498c-83b1-04bcb1bb0a74.png)

## expected result
enter the rstudio

## more information
I can enter docker started pure `rocker/rstudio`
I've tested this repo on my own arch installation and a centos 7 server, same result

tried `rocker/rstudio:3.6.3` problem exists

**Comment by TTTPOB** [comment]
(
sorry, the problem cease to exist for no reason(

**Comment by EasyPiPi** [comment]
Hi TTTPOB, I'm wondering how you get the problem fixed? I spent two days playing with this repo, and now I can get things to work with the docker version. 

However, when I tried the Singularity version, the login page of rstudio server keeps prompting me incorrect username or password. Therefore, I have to make --auth-none=1 to skip the authentication. It would be great if you can share with me your solution.
