### ISSUE TITLE
cannot clone

### ISSUE THREAD

**Issue by sdsnature** [grst/rstudio-server-conda#30]
ubuntu@VM-8-7-ubuntu:~$ git clone git@github.com:grst/rstudio-server-conda.git
Cloning into 'rstudio-server-conda'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by grst** [comment]
Hi, 

please make sure to either set up your SSH public key in github, or use the `https` URL for cloning. 

Cheers,
G
