### ISSUE TITLE
How to close R studio server? And access terminal while server is running?

### ISSUE THREAD

**Issue by andreasgoteson** [grst/rstudio-server-conda#4]
Bit of a newbie here, but when I run R studio server the regular way using r-base on ubuntu i can start and stop the server from terminal, also I can still access my terminal while running r studio server. But when I run it this way the terminal is not accessible and if I stop the session from R studio server menu nothing happens in command line?

**Comment by grst** [comment]
Hi @andreasgoteson, 

thanks for your question. I'm not sure if I understand your issue correctly, but, 

* it is normal behavior that your terminal is blocked while rstudio server is running when you start it the way described in this package. You can move it to background using `Ctrl + Z` or, simply start a second terminal window. 
* Stopping the session does not terminate the server. I wouldn't expect anything to happend on the command line. However if you start a new session (or restart the session) you should see something like `current env is ...` on the command line. 
* To stop the server, use `Ctrl + C`

The `Ctrl + ` commands are not specific to this project, and I recommend you to familarize yourself with these essential linux commands ;)

**Comment by andreasgoteson** [comment]
Like I said - newbie questions. Now I get it! Thx

**Comment by grst** [comment]
> But running R-studio server the general way (using R-base outside conda
env and calling 'rstudio-server start') does not block the terminal.

Usually, rstudio-server starts a "Daemon" that runs in the background. This
is not compatible with the conda-approach.

>So do I simple close the server by closing the terminal window
Yes, or `Ctrl + C`.
