### ISSUE TITLE
secure-cookie-key-file Error

### ISSUE THREAD

**Issue by jtelleriar** [grst/rstudio-server-conda#5]
When connecting to some AWS's EMR Clusters, I am getting **"secure-cookie-key-file"** error, as not being a recognized launch statement.

Is this a know behaviour?

By skipping such --secure-cookie-key-file option I am able to launch RStudio Server however. Is it safe to do so?

Thanks.
Juan

**Comment by grst** [comment]
Hmm weird. Are you sure you have the latest version of Rstudio there? 

Regarding the safety: Apparently there are some security issues with this way of launching rstudio anyway (#3). I wouldn't use it outside a secure network anyway.

**Comment by jtelleriar** [comment]
It was RStudio 1.1, just checked it out.

Afterwards, I upgraded to RStudio 1.2. However, I am also having the
following issue: "error while loading shared libraries: libssl.so.1.1:
cannot open shared object file: No such file or directory".

Will continue investigating.

Thanks for fast response.
Juan

**Comment by jtelleriar** [comment]
The error I get now exactly with the latest version of RStudio is:

```{r}
/usr/lib/rstudio-server/bin/rserver: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

```

**Comment by grst** [comment]
Can you check if openssl is installed in the conda env you are launching
rstudio from?

**Comment by jtelleriar** [comment]
I created a separate issue, will close this and continue the conversation in the other.

Thanks!
Juan

**Comment by jtelleriar** [comment]
I checked so, and it is installed.

I think the issue is due to the fact that the os can only have
libssl.so.1.0 installed, and with the latest version of RStudio Server this
is no longer supported.
