### ISSUE TITLE
Error when launching RStudio Server: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jtelleriar** [grst/rstudio-server-conda#6]
With the latest version of RStudio:

```
wget https://download2.rstudio.org/server/centos6/x86_64/rstudio-server-rhel-1.2.5033-x86_64.rpm
sudo yum install rstudio-server-rhel-1.2.5033-x86_64.rpm
```

I am getting the following error when trying to launch RStudio Server:

```
error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

Any Solution? It might be due to a " libssl.so.1.1" installation issue probably.

**Comment by jtelleriar** [comment]
So when installing RStudio to the latest version, this has generated a conflict with my "old" Anaconda Environment.

By updating Openssl to the latest version, I shall be able to make it work again:

```
conda install -c anaconda openssl 

```

Will check such hypothesis, and if definitely is so, will submit a small pull request for the README file,  if you agree, in order to notice users that such issues can occur. 

Similar to "F.A.Q." Section.

Thanks!
Juan

**Comment by grst** [comment]
sure, that would be appreciated!

**Comment by jtelleriar** [comment]
https://github.com/rstudio/rstudio/issues/6006

Is is an issue related to the version of RStudio Server used, not this reporitory's RStudio Server Launch Configuration.

Will close for now.

Thanks!
Juan
